#!/usr/bin/env python3
"""Regenerates qml/icons.js from icons/*.svg (docs/87): Icon draws the design's stroke
icons from this table with the colour written into the SVG (exact in every state)."""
import json
import pathlib
import re

here = pathlib.Path(__file__).parent
bodies = {}
for path in sorted((here / 'icons').glob('*.svg')):
    svg = path.read_text()
    bodies[path.stem] = re.search(r'<svg[^>]*>(.*)</svg>', svg, re.S).group(1).strip()
(here / 'qml/icons.js').write_text(
    '// Generated by make-icons.py from icons/*.svg: do not edit.\n.pragma library\n\n'
    'var bodies = ' + json.dumps(bodies, indent=1, ensure_ascii=False) + ';\n\n'
    '// The icon as an SVG document, drawn in `color` (#rrggbb).\n'
    'function svg(name, color) {\n'
    '    var body = bodies[name];\n'
    '    if (body === undefined) return "";\n'
    '    return \'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" \'\n'
    '        + \'stroke="\' + color + \'" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">\'\n'
    '        + body.replace(/#000/g, color) + "</svg>";\n'
    '}\n')
print(len(bodies), 'icons')
