// Generated by make-icons.py from icons/*.svg: do not edit.
.pragma library

var bodies = {
 "alert": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 7.5v5.5\"/><path d=\"M12 16.3v.2\"/>",
 "back": "<path d=\"M15 5l-7 7 7 7\"/>",
 "camera": "<path d=\"M4 8h3l2-2.5h6L17 8h3v11H4z\"/><circle cx=\"12\" cy=\"13\" r=\"3.5\"/>",
 "check": "<path d=\"M5 12.5l4.5 4.5L19 7.5\"/>",
 "chevron-down": "<path d=\"M5 9l7 7 7-7\"/>",
 "chevron": "<path d=\"M9 5l7 7-7 7\"/>",
 "close": "<path d=\"M7 7l10 10\"/><path d=\"M17 7L7 17\"/>",
 "compose": "<path d=\"M4 20h4L19 9l-4-4L4 16z\"/><path d=\"M13.5 6.5l4 4\"/>",
 "copy": "<rect x=\"8\" y=\"8\" width=\"11\" height=\"12\" rx=\"2\"/><path d=\"M5 15V6a2 2 0 0 1 2-2h8\"/>",
 "download": "<path d=\"M12 4v11\"/><path d=\"M7 10l5 5 5-5\"/><path d=\"M5 20h14\"/>",
 "external": "<path d=\"M14 5h5v5\"/><path d=\"M19 5l-8 8\"/><path d=\"M18 14v5H5V6h5\"/>",
 "eye-off": "<path d=\"M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/><path d=\"M4 4l16 16\"/>",
 "eye": "<path d=\"M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/>",
 "file": "<path d=\"M6 3.5h8l4 4v13H6z\"/><path d=\"M14 3.5v4h4\"/>",
 "hang-up": "<path d=\"M3 13.5c5-4.5 13-4.5 18 0l-2 3-3.5-1.2v-2.6a10 10 0 0 0-5 0v2.6L7 16.5z\"/>",
 "headset": "<path d=\"M4 17v-4a8 8 0 0 1 16 0v4\"/><rect x=\"4\" y=\"14\" width=\"4\" height=\"6\" rx=\"1\"/><rect x=\"16\" y=\"14\" width=\"4\" height=\"6\" rx=\"1\"/>",
 "image": "<rect x=\"3.5\" y=\"4.5\" width=\"17\" height=\"15\" rx=\"2\"/><circle cx=\"9\" cy=\"10\" r=\"1.8\"/><path d=\"M20 16l-5-5-8 8.5\"/>",
 "key": "<circle cx=\"8\" cy=\"15\" r=\"4\"/><path d=\"M11 12l8-8\"/><path d=\"M16 7l2.5 2.5\"/><path d=\"M14 9l2 2\"/>",
 "keyboard": "<rect x=\"3\" y=\"6\" width=\"18\" height=\"12\" rx=\"2\"/><path d=\"M7 10h.01M11 10h.01M15 10h.01M7 14h10\"/>",
 "menu": "<path d=\"M4 7h16\"/><path d=\"M4 12h10\"/><path d=\"M4 17h16\"/>",
 "open-in-app": "<path d=\"M5 5h14v10H10l-4 4v-4H5z\"/>",
 "phone": "<path d=\"M6.5 3.5h3l1.5 4-2 1.5a11 11 0 0 0 6 6l1.5-2 4 1.5v3a2 2 0 0 1-2 2A16 16 0 0 1 4.5 5.5a2 2 0 0 1 2-2z\"/>",
 "plus": "<path d=\"M12 6v12\"/><path d=\"M6 12h12\"/>",
 "search": "<circle cx=\"10.5\" cy=\"10.5\" r=\"5.5\"/><path d=\"M15 15l5 5\"/>",
 "send": "<path d=\"M12 19V6\"/><path d=\"M6 11l6-6 6 6\"/>",
 "settings": "<circle cx=\"12\" cy=\"12\" r=\"3\"/><path d=\"M12 3v2.5M12 18.5V21M3 12h2.5M18.5 12H21M5.6 5.6l1.8 1.8M16.6 16.6l1.8 1.8M5.6 18.4l1.8-1.8M16.6 7.4l1.8-1.8\"/>",
 "speaker": "<path d=\"M4 10v4h4l5 4V6L8 10z\"/><path d=\"M16.5 9a4 4 0 0 1 0 6\"/>",
 "stop": "<rect x=\"7\" y=\"7\" width=\"10\" height=\"10\" rx=\"1.5\" fill=\"#000\" stroke=\"none\"/>",
 "terminal": "<rect x=\"3.5\" y=\"5\" width=\"17\" height=\"14\" rx=\"1.5\"/><path d=\"M7.5 10l3 2.5-3 2.5\"/><path d=\"M12.5 15.5h4\"/>",
 "text": "<path d=\"M5 6h14\"/><path d=\"M12 6v13\"/><path d=\"M9 19h6\"/>",
 "voice": "<path d=\"M6 10v4\"/><path d=\"M10 7v10\"/><path d=\"M14 9v6\"/><path d=\"M18 11v2\"/>"
};

// The icon as an SVG document, drawn in `color` (#rrggbb).
function svg(name, color) {
    var body = bodies[name];
    if (body === undefined) return "";
    return '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" '
        + 'stroke="' + color + '" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">'
        + body.replace(/#000/g, color) + "</svg>";
}
