#!/bin/sh
set -e
# The wrapper takes /usr/bin/firefox; Mozilla's package keeps its file as firefox.moto-orig
# (a package diversion: dpkg keeps it through Firefox upgrades).
if [ "$1" = install ] || [ "$1" = upgrade ]; then
    dpkg-divert --package moto-firefox --add --rename --divert /usr/bin/firefox.moto-orig /usr/bin/firefox
fi
