name: rungic-server
services:
  web:
    image: nginx:alpine
    container_name: rungic-nginx
    restart: unless-stopped
    ports:
      - "18088:80"
    volumes:
      - webdata:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "wget", "-Y", "off", "-q", "-O", "/dev/null", "http://127.0.0.1/"]
      interval: 30s
      timeout: 5s
      retries: 3
volumes:
  webdata:
