#!/data/data/com.termux/files/usr/bin/bash
set -eu
case ${0##*/} in
    docker) root_command='/data/adb/moto-docker/moto-docker cli';;
    docker-service) root_command='/data/adb/moto-docker/moto-docker';;
    *) exit 2;;
esac
for arg in "$@"; do
    escaped=${arg//\'/\'\\\'\'}
    root_command+=" '$escaped'"
done
unset LD_PRELOAD LD_LIBRARY_PATH
if [[ -t 0 && -t 1 ]]; then
    exec /product/bin/su -i -c "$root_command"
fi
exec /product/bin/su -c "$root_command"
