#!/bin/sh
# Private FFmpeg; all other applications keep the distribution libraries.
export LD_LIBRARY_PATH=/usr/lib/firefox:/usr/lib/rungic-codec/ffmpeg/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export LD_PRELOAD=/usr/lib/rungic-codec/libmotocodec.so:/usr/lib/firefox/libavcodec.so.62${LD_PRELOAD:+:$LD_PRELOAD}
export RUNGIC_CODEC_PRECONNECT=1
exec /usr/lib/firefox/firefox "$@"
