#!/bin/sh
set -eu
width=720
height=1600
if [ -f /mnt/android-wayland/android-display.ini ]; then
    width=$(sed -n 's/^width=\([0-9]*\)$/\1/p' /mnt/android-wayland/android-display.ini)
    height=$(sed -n 's/^height=\([0-9]*\)$/\1/p' /mnt/android-wayland/android-display.ini)
fi
export MOTO_KWIN_ANDROID_SHM=1
export MOTO_KWIN_FLAT_OUTPUT=1
# Mobile input fields should summon the OSK even after a synthetic pointer event.
export KWIN_IM_SHOW_ALWAYS=1
scale=$(awk -v w="$width" -v h="$height" 'BEGIN { edge=(w<h?w:h); print edge / 360 }')
width=$(awk -v w="$width" -v s="$scale" 'BEGIN { printf "%d", w/s }')
height=$(awk -v h="$height" -v s="$scale" 'BEGIN { printf "%d", h/s }')
exec /usr/bin/kwin_wayland_wrapper --wayland-display=/mnt/android-wayland/wayland-0 \
    --width="$width" --height="$height" --scale="$scale" --no-lockscreen
