cmake_minimum_required(VERSION 3.22)
project(MotoScreenRecorder)
set(QT_MAJOR_VERSION 6)
find_package(ECM REQUIRED NO_MODULE)
set(CMAKE_MODULE_PATH ${ECM_MODULE_PATH})
include(KDEInstallDirs)
include(KDECMakeSettings)
include(ECMQmlModule)
set(CMAKE_CXX_STANDARD 20)
find_package(Qt6 REQUIRED COMPONENTS Core Qml Quick DBus)
find_package(KF6 REQUIRED COMPONENTS CoreAddons I18n Notifications)
ecm_add_qml_module(recordplugin URI "org.kde.plasma.quicksetting.record" GENERATE_PLUGIN_SOURCE)
target_sources(recordplugin PRIVATE recordutil.cpp recordutil.h)
target_link_libraries(recordplugin PRIVATE Qt::Core Qt::Qml Qt::Quick KF6::CoreAddons KF6::I18n KF6::Notifications)
ecm_finalize_qml_module(recordplugin)
